import type { Metadata } from "next";
import { Cormorant_Infant } from "next/font/google";
import "./globals.css";
import MobileNavMenu from "./MobileNavMenu";
import Header from "./Header";
import { getMe } from "@/api/services/auth.server";
import TechLayer from "./TechLayer";
import LogoIcon from "./LogoIcon";

const cormorantInfant = Cormorant_Infant({
  variable: "--font-cormorant-infant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getMe();
  return (
    <html lang="en" className={`${cormorantInfant.variable} h-full antialiased`}>
      <body>
        <TechLayer user={user} />
        <LogoIcon className="text-logo-color pointer-events-none fixed top-1/2 left-1/2 z-[-1] h-auto w-full -translate-x-1/2 -translate-y-1/2 transform opacity-30 blur-[5px] sm:h-full sm:w-auto sm:blur-[10px]" />
        <Header />
        <MobileNavMenu />
        <main className="mt-22 sm:mt-32">{children}</main>
      </body>
    </html>
  );
}
