import type { Metadata } from "next";
import { Playpen_Sans, Great_Vibes } from "next/font/google";
import "./globals.css";
import MobileNavMenu from "./MobileNavMenu";
import Header from "./Header";

const tenorSans = Playpen_Sans({
  variable: "--font-tenor-sans",
  subsets: ["latin"],
  weight: "400",
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${tenorSans.variable} ${greatVibes.variable} h-full antialiased`}>
      <body>
        <Header />
        <MobileNavMenu />
        <main className="mt-16 sm:mt-25">{children}</main>
      </body>
    </html>
  );
}
