import type { Metadata } from "next";
import { Cormorant_Infant, Kurale, Caveat, Tenor_Sans, Montserrat } from "next/font/google";
import "./globals.css";
import { getMe } from "@/api/services/auth.server";
import TechLayer from "../../components/layout/TechLayer";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Header from "@/components/layout/Header";
import Background from "@/components/layout/Background";
import MobileNavMenu from "@/components/layout/MobileNavMenu";

const cormorantInfant = Cormorant_Infant({
  variable: "--font-cormorant-infant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const kurale = Kurale({
  variable: "--font-kurale",
  subsets: ["latin"],
  weight: ["400"],
});

const caveat = Caveat({
  variable: "--font-caveat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const tenorSans = Tenor_Sans({
  variable: "--font-tenor-sans",
  subsets: ["latin"],
  weight: ["400"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();
  const user = await getMe();
  return (
    <html
      lang={locale}
      className={`${cormorantInfant.variable} ${kurale.variable} ${caveat.variable} ${tenorSans.variable} ${montserrat.variable} h-full antialiased`}
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <TechLayer user={user} />
          <Header />
          <MobileNavMenu />
          <main className="z-10">{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
